extends Node

const RANDOMPOOL = true
#const RANDOMPOOL = false

const DUNGPATH = "res://databases/dungeons/default.json"
#const DUNGPATH = "res://dungeons/test_pass.json";const POOL1PATH = "res://dicepools/test_pass.json";const POOL2PATH = "res://dicepools/test_pass.json"
#const DUNGPATH = "res://dungeons/test_target.json";const POOL1PATH = "res://dicepools/test_target.json";const POOL2PATH = "res://dicepools/test_target.json"
#const DUNGPATH = "res://dungeons/test_power.json";const POOL1PATH = "res://dicepools/test_power.json";const POOL2PATH = "res://dicepools/test_power.json"
#const DUNGPATH = "res://dungeons/test_move.json";const POOL1PATH = "res://dicepools/test_move.json";const POOL2PATH = "res://dicepools/test_move.json"
#const DUNGPATH = "res://dungeons/test_items.json";const POOL1PATH = "res://dicepools/test_items.json";const POOL2PATH = "res://dicepools/test_items.json"
#const DUNGPATH = "res://dungeons/test_dim_abilities.json";const POOL1PATH = "res://dicepools/test_dim_abilities.json";const POOL2PATH = "res://dicepools/test_dim_abilities.json"
#const DUNGPATH = "res://dungeons/test_dim_buff_dead_type.json";const POOL1PATH = "res://dicepools/test_dim_buff_dead_type.json";const POOL2PATH = "res://dicepools/test_dim_buff_dead_type.json"
#const DUNGPATH = "res://dungeons/test_exodia.json";const POOL1PATH = "res://dicepools/test_exodia.json";const POOL2PATH = "res://dicepools/test_exodia.json"
#const DUNGPATH = "res://databases/dungeons/default.json";const POOL1PATH = "res://dicepools/test_bufftype.json";const POOL2PATH = "res://dicepools/test_bufftype.json"
#const DUNGPATH = "res://dungeons/test_stops.json";const POOL1PATH = "res://dicepools/test_stops.json";const POOL2PATH = "res://dicepools/test_stops.json"
#const DUNGPATH = "res://dungeons/test_protect_type.json";const POOL1PATH = "res://dicepools/test_protect_type.json";const POOL2PATH = "res://dicepools/test_protect_type.json"
#const DUNGPATH = "res://dungeons/test_turn_slow_type.json";const POOL1PATH = "res://dicepools/test_turn_slow_type.json";const POOL2PATH = "res://dicepools/test_turn_slow_type.json"
#const DUNGPATH = "res://dungeons/test_vortex.json";const POOL1PATH = "res://dicepools/test_vortex.json";const POOL2PATH = "res://dicepools/test_vortex.json"
#const DUNGPATH = "res://dungeons/test_raise_attack.json";const POOL1PATH = "res://dicepools/test_raise_attack.json";const POOL2PATH = "res://dicepools/test_raise_attack.json"
#const DUNGPATH = "res://dungeons/test_reduce_damage.json";const POOL1PATH = "res://dicepools/test_reduce_damage.json";const POOL2PATH = "res://dicepools/test_reduce_damage.json"
#const DUNGPATH = "res://dungeons/test_reply_abilities.json";const POOL1PATH = "res://dicepools/test_reply_abilities.json";const POOL2PATH = "res://dicepools/test_reply_abilities.json"
#const DUNGPATH = "res://dungeons/test_buff_self.json";const POOL1PATH = "res://dicepools/test_buff_self.json";const POOL2PATH = "res://dicepools/test_buff_self.json"
#const DUNGPATH = "res://dungeons/test_buff_damage.json";const POOL1PATH = "res://dicepools/test_buff_damage.json";const POOL2PATH = "res://dicepools/test_buff_damage.json"
#const DUNGPATH = "res://dungeons/test_distance_attack.json";const POOL1PATH = "res://dicepools/test_distance_attack.json";const POOL2PATH = "res://dicepools/test_distance_attack.json"
#const DUNGPATH = "res://dungeons/test_range_kill_all.json";const POOL1PATH = "res://dicepools/test_range_kill_all.json";const POOL2PATH = "res://dicepools/test_range_kill_all.json"
#const DUNGPATH = "res://dungeons/test_trade_health.json";const POOL1PATH = "res://dicepools/test_trade_health.json";const POOL2PATH = "res://dicepools/test_trade_health.json"
#const DUNGPATH = "res://dungeons/test_steal_monster.json";const POOL1PATH = "res://dicepools/test_steal_monster.json";const POOL2PATH = "res://dicepools/test_steal_monster.json"
#const DUNGPATH = "res://dungeons/test_mind_control.json";const POOL1PATH = "res://dicepools/test_mind_control.json";const POOL2PATH = "res://dicepools/test_mind_control.json"
#const DUNGPATH = "res://dungeons/test_kill_block.json";const POOL1PATH = "res://dicepools/test_kill_block.json";const POOL2PATH = "res://dicepools/test_kill_block.json"
#const DUNGPATH = "res://dungeons/test_range_level_kill.json";const POOL1PATH = "res://dicepools/test_range_level_kill.json";const POOL2PATH = "res://dicepools/test_range_level_kill.json"
#const DUNGPATH = "res://dungeons/test_roll_level_kill.json";const POOL1PATH = "res://dicepools/test_roll_level_kill.json";const POOL2PATH = "res://dicepools/test_roll_level_kill.json"
#const DUNGPATH = "res://dungeons/test_dim_kill_tunnel_all.json";const POOL1PATH = "res://dicepools/test_dim_kill_tunnel_all.json";const POOL2PATH = "res://dicepools/test_dim_kill_tunnel_all.json"
#const DUNGPATH = "res://dungeons/test_dim_trade_crest.json";const POOL1PATH = "res://dicepools/test_dim_trade_crest.json";const POOL2PATH = "res://dicepools/test_dim_trade_crest.json"
#const DUNGPATH = "res://dungeons/test_dim_kill_tunnel.json";const POOL1PATH = "res://dicepools/test_dim_kill_tunnel.json";const POOL2PATH = "res://dicepools/test_dim_kill_tunnel.json"
#const DUNGPATH = "res://dungeons/test_dim_kill_weakest.json";const POOL1PATH = "res://dicepools/test_dim_kill_weakest.json";const POOL2PATH = "res://dicepools/test_dim_kill_weakest.json"
#const DUNGPATH = "res://dungeons/test_monster_reborn.json";const POOL1PATH = "res://dicepools/test_monster_reborn.json";const POOL2PATH = "res://dicepools/test_monster_reborn.json"
#const DUNGPATH = "res://dungeons/test_dim_cure.json";const POOL1PATH = "res://dicepools/test_dim_cure.json";const POOL2PATH = "res://dicepools/test_dim_cure.json"
#const DUNGPATH = "res://dungeons/test_multi_attack.json";const POOL1PATH = "res://dicepools/test_multi_attack.json";const POOL2PATH = "res://dicepools/test_multi_attack.json"
#const DUNGPATH = "res://dungeons/test_negate_atk_abi.json";const POOL1PATH = "res://dicepools/test_negate_atk_abi.json";const POOL2PATH = "res://dicepools/test_negate_atk_abi.json"
